"""Original Polish scenarios, authored from permitted DK mechanism/use fields.

One scenario per knowledge record; no source_fact text or device thresholds.
Each tuple is (observations/question, hypothesis, test, discriminating outcomes).
"""
EXAMPLES = [
("Zawór ECU 12 V jest wyłączony, lecz na obu końcach cewki widać napięcie. Czy sterownik sam go załącza?", "Słaba polaryzacja diagnostyczna może ustalać napięcie bez prądu zdolnego poruszyć zawór.", "Ustal tryb OFF i schemat polaryzacji dla rozpoznanego sterownika; porównaj oba końce cewki oraz prąd z prawidłowym kanałem.", "Zgodne napięcia przy znikomym prądzie pasują do diagnostyki; istotny prąd mimo OFF wymaga sprawdzenia niezamierzonego przewodzenia."),
("Wtryskiwacz ma zgodne napięcia obu zacisków w spoczynku i prawidłowe flagi. Czy mogę potwierdzić jego sprawność?", "Wynik wspiera ciągłość toru przy słabej polaryzacji, ale nie potwierdza dynamiki ani działania mechanicznego.", "Na zabezpieczonym stanowisku porównaj narastanie prądu i napięcie pod kontrolowanym impulsem z poprawnym kanałem; nie uruchamiaj wtrysku paliwa bez procedury stanowiska.", "Prawidłowy spoczynek z odmiennym przebiegiem prądu ujawnia usterkę dynamiczną; zgodność elektryczna nadal nie dowodzi poprawnego rozpylania."),
("W trybie diagnostycznym OFF jeden koniec cewki pozostaje na poziomie polaryzacji, drugi dąży do szyny. Co rozdzielić?", "Przerwa może rozdzielać dwa słabe obwody polaryzacji; sama różnica napięć nie lokalizuje przerwy.", "Po wyłączeniu zasilania sprawdź oddzielnie cewkę, złącza i wiązkę; wcześniej potwierdź oczekiwaną topologię OFF.", "Przerwa samej cewki i przerwa wiązki dadzą różne wyniki pomiarów odcinkowych, choć napięcia na ECU mogą wyglądać podobnie."),
("Wyjście zaworu w OFF pozostaje przy masie mimo potwierdzonego słabego podciągania. Czy to przerwa?", "Twarda droga do masy może pokonać podciąganie; możliwe są zwarcie wiązki albo przewodzący stopień mocy.", "Odłącz zasilanie, rozdziel wiązkę od modułu i porównaj rezystancje do masy obu stron; uwzględnij diody i pozostałe ścieżki.", "Niska rezystancja po stronie wiązki zawęża zwarcie zewnętrzne; po stronie ECU wymaga dalszego badania stopnia, bez automatycznej wymiany MOSFET."),
("Wyjście high-side jest blisko akumulatora mimo OFF, a obciążenie pobiera prąd. Czy MOSFET jest zwarty?", "Możliwy jest zwarty stopień HS, ale także zasilanie zwrotne z innej gałęzi.", "Bezpiecznie odizoluj odbiornik od innych zasilań; po odłączeniu energii zbadaj tor stopnia i sprawdź sterowanie bramki względem źródła.", "Zanik napięcia po izolacji wskazuje zasilanie zwrotne; utrzymana ścieżka w module przy nieaktywnym sterowaniu wspiera uszkodzenie toru HS."),
("Zawór przechodzi test OFF, ale przestaje pracować po rozgrzaniu i obciążeniu. Czy wiązka jest wykluczona?", "Mały prąd diagnostyczny nie ujawnia rezystancyjnego styku ani usterki zależnej od temperatury.", "Rejestruj spadki napięcia na złączach i prąd podczas bezpiecznej próby pod obciążeniem, w stanie zimnym i ciepłym.", "Rosnący spadek na styku przy podobnym prądzie wskazuje lokalną rezystancję; wyłączenie bez takiego spadku kieruje do ochrony lub sterowania."),
("Rozpoznany high-side ma w OFF okno napięcia diagnostycznego. Wyjście wpada w środek tego okna. Jak sprawdzić otwarty obwód?", "Okno może oznaczać brak obciążenia wyłącznie przy aktywnej właściwej diagnostyce.", "Zweryfikuj konfigurację i czas ustalania; przy odłączonej energii sprawdź ciągłość odbiornika, następnie użyj zatwierdzonego obciążenia zastępczego.", "Przejście do stanu oczekiwanego po dołączeniu obciążenia wspiera przerwę zewnętrzną; brak reakcji wymaga badania diagnostycznego źródła i konfiguracji."),
("Low-side w OFF zgłasza błąd, a węzeł jest przy masie. Czy można zastosować tabelę high-side?", "Interpretacja zależy od położenia obciążenia i źródeł polaryzacji; tabela HS może prowadzić do błędnego wniosku.", "Narysuj tor od zasilania przez cewkę do LS; potwierdź aktywny tryb diagnostyczny i sprawdź rozdzielone gałęzie bez zasilania.", "Twarda droga do masy i odłączona cewka są rozróżnialne pomiarem odcinkowym; same nazwy flag bez topologii nie wystarczają."),
("Przy dużym wypełnieniu PWM diagnostyka przerwy przestaje działać. Przy długim OFF działa. Co zmierzyć?", "Próbka może przypadać przed ustaleniem napięcia albo po ponownym załączeniu.", "Zarejestruj na jednej osi czasu PWM, napięcie węzła i moment diagnostyki; porównaj okno OFF z wymaganiami rozpoznanego układu.", "Brak czasu na ustalenie tłumaczy utratę obserwowalności; poprawne okno z utrzymanym błędem wymaga badania rzeczywistego toru."),
("Sterownik solenoidu zgłasza zwarcie tylko po zmianie częstotliwości PWM. Czy wymienić stopień?", "Flaga może wynikać z próbkowania przejścia indukcyjnego, a nie trwałego zwarcia.", "Przy ograniczonej energii porównaj przebieg wygaszania cewki i czas odczytu flag przed oraz po zmianie PWM, utrzymując porównywalny prąd.", "Flaga związana wyłącznie z przejściem sugeruje artefakt czasowy; utrzymana droga zwarcia poza przejściem wymaga lokalizacji fizycznej."),
("Po naprawie wiązki błąd drivera nie znika przy samym odczycie SPI. Co sprawdzić przed kolejną naprawą?", "Stan zatrzaśnięty może wymagać określonego przejścia trybu; odczyt nie musi kasować błędu.", "Zachowaj pierwszy odczyt i warunki, rozpoznaj układ, wykonaj udokumentowaną bezpieczną sekwencję kasowania, po czym odtwórz test.", "Brak nawrotu po prawidłowym kasowaniu wspiera historyczny błąd; powrót w określonym stanie wskazuje aktywną przyczynę."),
("Po dwóch kolejnych usterkach SPI stale pokazuje pierwszą. Czy druga próba wykluczyła nową usterkę?", "Priorytet i zatrzask flag mogą zasłaniać późniejsze zdarzenie.", "Zapisz kolejność zdarzeń; po usunięciu pierwszej przyczyny i bezpiecznym kasowaniu sprawdź osobno drugą, zgodnie z maszyną stanów układu.", "Pojawienie się drugiej flagi po kasowaniu potwierdza maskowanie; brak flagi nie zastępuje pomiaru fizycznego."),
("Nie znam odmiany drivera. Mam napięcie OFF i chcę użyć progów z podobnego układu. Czy rozpoznam przerwę?", "Różne progi, prądy polaryzacji i filtry czasu mogą zmienić klasyfikację tego samego pomiaru.", "Najpierw ustal oznaczenie i wariant, konfigurację oraz czas od włączenia diagnostyki; bez nich ogranicz się do bezpiecznych pomiarów ciągłości.", "Dopiero zweryfikowane warunki pozwalają porównać napięcie z progiem; przy nieznanym wariancie klasyfikacja pozostaje nierozstrzygnięta."),
("Przy OFF zerowy prąd high-side pasuje zarówno do przerwy, jak i zewnętrznego zwarcia do plusa. Jaki test rozdzieli?", "Pomiar bierny może nie odróżniać dwóch stanów; potrzebna jest kontrolowana zmiana słabej polaryzacji.", "Dla rozpoznanego układu użyj wyłącznie przewidzianej funkcji diagnostycznej i obserwuj reakcję wyjścia; nie zwieraj aktywnego wyjścia ani nie podawaj napięcia na nieznany pin.", "Węzeł swobodny reaguje na słabą zmianę polaryzacji, twardo połączony z plusem pozostaje przy szynie; interpretacja wymaga potwierdzonej topologii."),
("Komenda HS jest aktywna i VOUT wygląda poprawnie, ale sense wskazuje brak prądu. Czy odbiornik działa?", "Poprawne napięcie bez prądu może oznaczać przerwę, lecz możliwy jest też błąd toru sense lub jego skalowania.", "Porównaj niezależny pomiar prądu z sense, napięciem na obciążeniu i flagą w tym samym stanie; sprawdź rezystor i odniesienie wejścia ADC.", "Prąd niezależny przy zerowym sense zawęża tor pomiarowy; brak obu prądów kieruje do ciągłości obciążenia."),
("CAN zgłasza błędy, a moduł ma transceiver z diagnostyką zwarć. Czy liczniki kontrolera wystarczą?", "Diagnostyka transceivera może dostarczać inną informację niż błędy ramek, o ile konkretny wariant ją obsługuje.", "Ustal oznaczenie i tryb transceivera, zachowaj jego flagi oraz zmierz CAN-H i CAN-L względem lokalnej masy przy użyciu właściwej sondy.", "Zgodność flagi z napięciem przy szynie wspiera zwarcie fizyczne; rozbieżność wymaga sprawdzenia trybu, czasu odczytu i masy."),
("Ramki CAN nadal przechodzą, ale pojazd ma zakłócenia po dołączeniu odbiornika mocy. Czy warstwa fizyczna jest zdrowa?", "Odbiornik różnicowy może działać mimo nieprawidłowego poziomu wspólnego i małego zapasu odporności.", "Porównaj oba przewody względem masy i sygnał różnicowy podczas przełączania odbiornika; sprawdź spadki mas między modułami.", "Przesunięcie obu linii wraz ze spadkiem masy wskazuje problem odniesienia; deformacja różnicowa kieruje również do terminacji i odgałęzień."),
("Nie ma flagi zwarcia w transceiverze CAN, lecz brak komunikacji. Czy wykluczyć wiązkę?", "Detektor może mieć ślepe obszary albo wymagać określonego stanu magistrali.", "Sprawdź zakres detekcji dla układu; bez zasilania zmierz ciągłość i terminację, potem w bezpiecznych warunkach obserwuj TXD, RXD oraz obie linie.", "Aktywne TXD bez poprawnego przebiegu na magistrali zawęża transceiver lub tor; brak TXD kieruje też do sterowania, resetu i trybu pracy."),
("Nieznany ECU nie komunikuje się. Na złączu jest zasilanie. Od czego rozpocząć mapowanie PCB?", "Obecność napięcia na złączu nie potwierdza zasilania MCU, referencji czujników ani zwolnienia resetu.", "Bez zgadywania pinów prześledź ochronę wejścia, przetwornicę wstępną, szynę MCU, gałęzie czujników, reset i zasilanie sieci; zanotuj punkty odniesienia.", "Pierwsza nieprawidłowa domena zawęża dalsze pomiary; prawidłowe domeny z aktywnym resetem kierują do nadzoru zamiast wymiany MCU."),
("Zwarcie referencji 5 V czujnika daje DTC, ale ECU nadal odpowiada. Czy zasilanie MCU jest uszkodzone?", "Szyna czujników i szyna MCU mogą mieć odrębne ograniczenia oraz różny wpływ na reset.", "Obserwuj jednocześnie obie szyny i reset; po wyłączeniu zasilania odłącz podejrzaną gałąź czujnika i powtórz pomiar z ograniczeniem prądu.", "Powrót referencji bez zmiany szyny MCU wskazuje lokalne przeciążenie; wspólny zapad wymaga szukania współdzielonego toru wejściowego."),
("Zasilania ECU są stabilne, lecz kilka wyjść i komunikacja są zablokowane. Czy uszkodziło się wiele driverów?", "PMIC lub watchdog może celowo utrzymywać wspólny stan bezpieczny mimo poprawnych napięć.", "Zarejestruj reset, enable i obsługę watchdog wraz ze statusem PMIC; sprawdź sekwencję uruchomienia bez obchodzenia zabezpieczeń.", "Wspólna blokada zgodna ze stanem nadzoru kieruje do jej przyczyny; niezależne błędy po zwolnieniu blokady uzasadniają badanie kanałów."),
("ECU 12 V jest martwy, napięcie dochodzi do elementu wejściowego, ale nie do przetwornicy. Jak uniknąć pochopnej wymiany MCU?", "Tor ochrony lub jego sterowanie może odcinać energię przed przetwornicą.", "Zmierz obie strony ochrony i VGS tranzystora względem jego źródła, następnie stan kontrolera i rezystancję dalszej szyny przy odłączonym zasilaniu.", "Brak sterowania wskazuje nadzór lub warunki wejścia; prawidłowe sterowanie z dużym spadkiem na torze zawęża element lub połączenie."),
("Po impulsie na zasilaniu wejściowy MOSFET przestał przewodzić. Po kontrolowanym restarcie tor wraca. Co to znaczy?", "Zatrzaśnięta ochrona może naśladować trwałe uszkodzenie elementu mocy.", "Zachowaj status kontrolera i przebieg bramki przed restartem; sprawdź obciążenie oraz przyczynę zadziałania, nie wymuszaj przewodzenia bramki.", "Powrót po prawidłowym skasowaniu potwierdza zależność od stanu ochrony, lecz nie dowodzi braku przeciążenia lub uszkodzeń następczych."),
("ECU 12 V resetuje się tylko przy rozruchu, po starcie miernik pokazuje poprawne zasilanie. Co zarejestrować?", "Krótki zapad lub skok potencjału masy może występować wyłącznie podczas dużego prądu rozrusznika.", "Wyzwól oscyloskop na reset; równolegle obserwuj wejście ECU względem jego masy, szynę MCU i spadek masy do akumulatora, bez zwierania mas sond.", "Zapad wejścia przed resetem wspiera problem doprowadzenia energii; stabilne wejście z zapadem szyny zawęża przetwarzanie lokalne."),
("Sterownik pojazdu 24 V przestał działać po zdarzeniu ładowania. Czy elementy wystarczy sprawdzić względem nominalnych 24 V?", "Naprężenie przejściowe może być dużo większe niż nominalne zasilanie; sam pomiar napięcia obecnego nie odtwarza historii.", "Bez generowania przepięć sprawdź ochronę wejścia, elementy ograniczające, kondensatory i przetwornicę; dobór zamiennika oprzyj na zweryfikowanych wymaganiach modułu.", "Uszkodzenia skoncentrowane na wejściu wspierają ścieżkę przepięciową; brak widocznych śladów nie wyklucza uszkodzenia i wymaga pomiarów."),
("Smart switch nie przewodzi po spadku zasilania. Czy brak wyjścia dowodzi przerwanego MOSFET?", "Aktywna ochrona podnapięciowa lub stan po niewłaściwej polaryzacji może blokować sprawny tor.", "Sprawdź napięcie przy samym układzie, masę, enable i flagi; odtwórz poprawne warunki oraz udokumentowany restart przy ograniczonej energii.", "Powrót wyjścia po usunięciu przyczyny wspiera blokadę ochronną; trwały brak wymaga dalszego rozdzielenia sterowania i toru mocy."),
("Zasilanie solenoidu pojawia się impulsowo mimo stałej komendy. Czy sterownik oscyluje z powodu uszkodzenia?", "Możliwa jest cykliczna ochrona przeciążeniowa, ograniczenie prądu albo restart termiczny.", "Zarejestruj prąd, napięcie wyjścia i flagę razem; porównaj z udokumentowanym trybem ochrony oraz zatwierdzonym obciążeniem zastępczym.", "Zanik cykli po usunięciu przeciążenia wskazuje reakcję ochronną; cykle bez nadmiernego prądu wymagają sprawdzenia zasilania, temperatury i sterowania."),
("Chcę tworzyć syntetyczne przypadki awarii wtryskiwacza. Czy wynik symulatora producenta można opisać jako pomiar ECU?", "Model pomaga wymusić spójne mechanizmy, ale jego wynik zależy od parametrów i nie jest dowodem z naprawy rzeczywistego modułu.", "Zapisz model, wersję, warunki i wprowadzoną usterkę; porównaj stan poprawny z pojedynczym zaburzeniem i oznacz wynik jako symulację.", "Zmiana zgodna z modelem uzasadnia przykład szkoleniowy w jego zakresie; niezgodność lub brak modelu wymaga ograniczenia twierdzeń zamiast wymyślania pomiarów."),
]
EXTRA = [
("Mostek H silnika działa tylko w jednym kierunku. Czy bezpiecznie wymusić oba górne klucze?", "Asymetria może wynikać z jednej gałęzi, jej sterowania, pomiaru prądu albo połączeń; wymuszanie kluczy grozi zwarciem szyny.", "Na zabezpieczonym stanowisku porównaj obie przekątne przy małej energii: napięcia bramka–źródło, napięcia zacisków silnika i prąd; zachowaj dead-time i ograniczenie prądu.", "Brak sterowania tylko w jednej gałęzi zawęża logikę lub driver; sterowanie poprawne przy dużym spadku kieruje do toru mocy. Nie omijaj blokad mostka."),
("CAN działa przy wolnej transmisji, a CAN-FD gubi ramki w szybkiej fazie danych. Czy to błąd identyfikatora J1939?", "Margines czasowy i odbicia w warstwie fizycznej mogą wystarczać dla wolnej fazy, lecz nie dla szybkiej; sam objaw nie wskazuje protokołu wyższego poziomu.", "Sprawdź zgodność transceiverów i konfigurację bit timing; zmierz różnicowy przebieg przy końcach magistrali, zweryfikuj terminację i długość odgałęzień bez zasilania.", "Odbicia i wolne zbocza skorelowane z błędami fazy danych wskazują tor fizyczny; poprawny przebieg wymaga kontroli zegarów i konfiguracji. Nie wyprowadzaj stanu fizycznego wyłącznie z adresów J1939."),
]
