#!/usr/bin/env bash
set -euo pipefail
ROOT="${HOME}/AI-server";BRANCH="feat/telegram-global-queue-status";WT="${HOME}/AI-server-global-resource-queue-install";BACKUP="/srv/ai-data/hermes/global-resource-queue-backup-v1"
HERMES_HOME="/srv/ai-data/hermes";HERMES_SOURCE="${HERMES_HOME}/hermes-agent";HERMES_PY="${HERMES_SOURCE}/venv/bin/python";HERMES_TURN="${HERMES_SOURCE}/agent/turn_api_request.py";HERMES_EXPECTED="79445a496c86a19332ad786494b8384d2167e2d0"
GATEWAY_HOME="/opt/ai-gateway";GATEWAY_PY="${GATEWAY_HOME}/.venv/bin/python";GATEWAY_SRC="${GATEWAY_HOME}/src/ai_bridge";LIBEXEC="/usr/local/libexec/ai-server";SUCCESS=0;MUTATED=0
say(){ printf '%s\n' "$*"; };fail(){ say "FAIL: $*" >&2;exit 1; }
backup_optional(){ local src="$1" name="$2";if [[ -e "$BACKUP/$name" || -e "$BACKUP/$name.absent" ]];then return;fi;if sudo test -e "$src";then sudo cp -a "$src" "$BACKUP/$name";else : > "$BACKUP/$name.absent";fi; }
restore_optional(){ local dst="$1" name="$2";if [[ -e "$BACKUP/$name.absent" ]];then sudo rm -f "$dst";elif [[ -e "$BACKUP/$name" ]];then sudo cp -a "$BACKUP/$name" "$dst";fi; }
restore_all(){ [[ -d "$BACKUP" ]] || return 0;restore_optional "$GATEWAY_SRC/gateway/scheduler.py" gateway-scheduler.py;restore_optional "$GATEWAY_SRC/gateway/resource_leases.py" gateway-resource_leases.py;restore_optional "$GATEWAY_SRC/gateway/app.py" gateway-app.py;restore_optional "$GATEWAY_SRC/settings.py" gateway-settings.py;if [[ -x "$GATEWAY_PY" ]];then sudo -u harrypotter "$GATEWAY_PY" -m pip install --disable-pip-version-check "$GATEWAY_HOME" >/dev/null 2>&1 || true;sudo systemctl restart ai-gateway.service >/dev/null 2>&1 || true;fi;restore_optional "$HERMES_TURN" hermes-turn_api_request.py;restore_optional /usr/local/bin/hermes-foto-dispatch hermes-foto-dispatch;restore_optional "$LIBEXEC/hermes_foto_dispatch_base.py" hermes_foto_dispatch_base.py;restore_optional "$LIBEXEC/hermes_resource_queue.py" hermes_resource_queue.py;restore_optional "$LIBEXEC/hermes_video_dispatch.py" hermes_video_dispatch.py;restore_optional "$LIBEXEC/hermes_video_dispatch_stage30.py" hermes_video_dispatch_stage30.py;systemctl --user restart hermes-gateway.service >/dev/null 2>&1 || true; }
cleanup(){ rc=$?;trap - EXIT INT TERM;if [[ "$SUCCESS" -ne 1 && "$MUTATED" -eq 1 ]];then echo;echo "===== AUTOMATIC ROLLBACK =====";restore_all;fi;if [[ -d "$WT" ]];then git -C "$ROOT" worktree remove --force "$WT" >/dev/null 2>&1 || true;fi;exit "$rc"; };trap cleanup EXIT INT TERM
[[ -d "$ROOT/.git" ]] || fail "repo missing: $ROOT";[[ -x "$HERMES_PY" ]] || fail "Hermes Python missing";[[ -x "$GATEWAY_PY" ]] || fail "AI Gateway Python missing";[[ "$(git -C "$HERMES_SOURCE" rev-parse HEAD)" == "$HERMES_EXPECTED" ]] || fail "unsupported Hermes checkout";[[ "$(systemctl is-active ai-gateway.service 2>/dev/null || true)" == active ]] || fail "ai-gateway.service inactive";[[ "$(systemctl --user is-active hermes-gateway.service 2>/dev/null || true)" == active ]] || fail "hermes-gateway.service inactive"
echo "===== FETCH TESTED FEATURE BRANCH =====";cd "$ROOT";git fetch origin main "$BRANCH";[[ "$(git rev-parse origin/main)" == "92ceea7bc4bc2b2af30da313b22108e9d686c265" ]] || fail "main changed; revalidate before install";if [[ -d "$WT" ]];then git worktree remove --force "$WT" >/dev/null 2>&1 || true;fi;git worktree add --detach "$WT" "origin/$BRANCH";say "feature: $(git -C "$WT" rev-parse --short HEAD)"
echo;echo "===== IDLE PRECHECK =====";"$GATEWAY_PY" - <<'PY'
import json,urllib.request
with urllib.request.urlopen("http://127.0.0.1:11435/status",timeout=3) as r:s=json.load(r)
print(json.dumps(s,ensure_ascii=False));assert s.get("active_count")==0 and s.get("queued_count")==0,"AI Gateway is busy"
PY
echo;echo "===== STATIC VALIDATION =====";"$GATEWAY_PY" -m py_compile "$WT/src/ai_bridge/gateway/scheduler.py" "$WT/src/ai_bridge/gateway/resource_leases.py" "$WT/src/ai_bridge/gateway/app.py" "$WT/src/ai_bridge/settings.py";"$HERMES_PY" -m py_compile "$WT/tools/hermes_resource_queue.py" "$WT/tools/patch_hermes_global_resource_queue.py" "$WT/tools/local_image/hermes_foto_dispatch_global.py" "$WT/tools/local_video/hermes_video_dispatch_global.py";patch_state="$("$HERMES_PY" "$WT/tools/patch_hermes_global_resource_queue.py" "$HERMES_TURN" --check)" || fail "Hermes patch unsupported: $patch_state";say "Hermes queue patch: $patch_state"
echo;echo "===== BACKUP =====";mkdir -p "$BACKUP";chmod 700 "$BACKUP";backup_optional "$GATEWAY_SRC/gateway/scheduler.py" gateway-scheduler.py;backup_optional "$GATEWAY_SRC/gateway/resource_leases.py" gateway-resource_leases.py;backup_optional "$GATEWAY_SRC/gateway/app.py" gateway-app.py;backup_optional "$GATEWAY_SRC/settings.py" gateway-settings.py;backup_optional "$HERMES_TURN" hermes-turn_api_request.py;backup_optional /usr/local/bin/hermes-foto-dispatch hermes-foto-dispatch;backup_optional "$LIBEXEC/hermes_foto_dispatch_base.py" hermes_foto_dispatch_base.py;backup_optional "$LIBEXEC/hermes_resource_queue.py" hermes_resource_queue.py;backup_optional "$LIBEXEC/hermes_video_dispatch.py" hermes_video_dispatch.py;backup_optional "$LIBEXEC/hermes_video_dispatch_stage30.py" hermes_video_dispatch_stage30.py;say "PASS: reversible backup ready";MUTATED=1
echo;echo "===== INSTALL GLOBAL RESOURCE MANAGER =====";sudo install -o harrypotter -g harrypotter -m 0644 "$WT/src/ai_bridge/gateway/scheduler.py" "$GATEWAY_SRC/gateway/scheduler.py";sudo install -o harrypotter -g harrypotter -m 0644 "$WT/src/ai_bridge/gateway/resource_leases.py" "$GATEWAY_SRC/gateway/resource_leases.py";sudo install -o harrypotter -g harrypotter -m 0644 "$WT/src/ai_bridge/gateway/app.py" "$GATEWAY_SRC/gateway/app.py";sudo install -o harrypotter -g harrypotter -m 0644 "$WT/src/ai_bridge/settings.py" "$GATEWAY_SRC/settings.py";sudo -u harrypotter "$GATEWAY_PY" -m pip install --disable-pip-version-check "$GATEWAY_HOME" >/dev/null;sudo systemctl restart ai-gateway.service
for _ in $(seq 1 60);do if "$GATEWAY_PY" - <<'PY' >/dev/null 2>&1
import json,urllib.request
with urllib.request.urlopen("http://127.0.0.1:11435/health",timeout=1) as r:h=json.load(r)
assert h.get("status")=="ok" and h.get("ollama")=="ok"
PY
then break;fi;sleep .25;done;[[ "$(systemctl is-active ai-gateway.service)" == active ]] || fail "AI Gateway failed after Resource Manager install"
echo;echo "===== SYNTHETIC GLOBAL QUEUE TEST =====";"$GATEWAY_PY" - <<'PY'
import json,urllib.request
base="http://127.0.0.1:11435"
def call(method,path,payload=None):
 data=json.dumps(payload).encode() if payload is not None else None;req=urllib.request.Request(base+path,data=data,method=method,headers={"Content-Type":"application/json"} if data else {})
 with urllib.request.urlopen(req,timeout=3) as r:return json.load(r)
a=call("POST","/resource/leases",{"source":"install-test-A","priority":50});b=call("POST","/resource/leases",{"source":"install-test-B","priority":50});assert a["state"]=="active" and b["state"]=="queued",(a,b);call("DELETE","/resource/leases/"+a["lease_id"]);b2=call("GET","/resource/leases/"+b["lease_id"]);assert b2["state"]=="active",b2;call("DELETE","/resource/leases/"+b["lease_id"])
with urllib.request.urlopen(base+"/status",timeout=3) as r:s=json.load(r)
assert s["active_count"]==0 and s["queued_count"]==0,s;print("PASS: active -> queued -> promoted -> released")
PY
echo;echo "===== INSTALL TELEGRAM CLIENT + MEDIA WRAPPERS =====";sudo install -d -m 0755 "$LIBEXEC";sudo install -m 0644 "$WT/tools/hermes_resource_queue.py" "$LIBEXEC/hermes_resource_queue.py";sudo install -m 0644 "$WT/tools/local_image/hermes_foto_dispatch.py" "$LIBEXEC/hermes_foto_dispatch_base.py";sudo install -m 0755 "$WT/tools/local_image/hermes_foto_dispatch_global.py" /usr/local/bin/hermes-foto-dispatch;sudo install -m 0755 "$WT/tools/local_video/hermes_video_dispatch_stage30.py" "$LIBEXEC/hermes_video_dispatch_stage30.py";sudo install -m 0755 "$WT/tools/local_video/hermes_video_dispatch_global.py" "$LIBEXEC/hermes_video_dispatch.py";"$HERMES_PY" "$WT/tools/patch_hermes_global_resource_queue.py" "$HERMES_TURN";"$HERMES_PY" -m py_compile "$HERMES_TURN";/usr/local/bin/hermes-foto-dispatch --preflight >/dev/null || fail "/foto preflight failed";/usr/local/bin/hermes-video-dispatch --qwen-preflight >/dev/null || fail "/wideo Qwen preflight failed"
echo;echo "===== RESTART HERMES ONLY =====";systemctl --user restart hermes-gateway.service;for _ in $(seq 1 60);do [[ "$(systemctl --user is-active hermes-gateway.service 2>/dev/null || true)" == active ]] && break;sleep .25;done;[[ "$(systemctl --user is-active hermes-gateway.service)" == active ]] || fail "Hermes failed to restart"
SUCCESS=1;MUTATED=0;echo;echo "===== DONE =====";say "PASS: global AI resource queue installed";say "Telegram gets wait/start notices only when it actually waits.";say "/foto and /wideo hold one shared lease across Qwen + ComfyUI.";say "Normal Telegram LLM requests reuse and auto-release the same scheduler lease.";say "Ventilation remains priority 10; Telegram/media priority 50.";say "No main merge was performed."
